# Generated by Django 2.0.6 on 2018-06-20 17:51

import apps.product.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('product_img_0', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.product.models.user_directory_path)),
                ('product_img_1', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.product.models.user_directory_path)),
                ('product_img_2', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.product.models.user_directory_path)),
                ('product_img_3', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.product.models.user_directory_path)),
                ('area', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('unit', models.CharField(default='', max_length=5)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('post_type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')], default=0)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('description', models.TextField(default='')),
                ('verify', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
