# Generated by Django 2.0.6 on 2018-06-14 07:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_img_0', models.ImageField(default='none/noimage.jpg', upload_to='product/')),
                ('product_img_1', models.ImageField(default=None, upload_to='product/')),
                ('product_img_2', models.ImageField(default=None, upload_to='product/')),
                ('product_img_3', models.ImageField(default=None, upload_to='product/')),
                ('area', models.IntegerField(default=0)),
                ('owner_id', models.IntegerField(default=0)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('description', models.TextField()),
            ],
        ),
    ]
