# Generated by Django 2.0.6 on 2018-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img_0',
            field=models.ImageField(default='image/none/noimage.jpg', upload_to='image/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_1',
            field=models.ImageField(default='image/none/noimage.jpg', upload_to='image/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_2',
            field=models.ImageField(default='image/none/noimage.jpg', upload_to='image/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_3',
            field=models.ImageField(default='image/none/noimage.jpg', upload_to='image/product/'),
        ),
    ]
