# Generated by Django 2.0.6 on 2018-06-20 17:51

import apps.user.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('factory_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('user_type', models.IntegerField(choices=[(0, 'Farmer'), (1, 'Factory')], default=0)),
                ('verify', models.BooleanField(default=False)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('age', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('prop_img_0', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
                ('prop_img_1', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
                ('prop_img_2', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
                ('prop_img_3', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
            ],
        ),
    ]
