# Generated by Django 2.0.6 on 2018-06-22 16:56

import apps.user.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(default='image/none/noimage.jpg', upload_to=apps.user.models.user_directory_path)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('authorize', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
        ),
    ]
