# Generated by Django 2.0.6 on 2018-06-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180622_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_account',
            field=models.BooleanField(default=False),
        ),
    ]
