# Generated by Django 2.0.6 on 2018-06-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tpe',
            field=models.CharField(default='', max_length=20),
        ),
    ]
