# Generated by Django 2.0.6 on 2018-06-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_user_tpe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_tpe',
            new_name='user_type',
        ),
    ]
