# Generated by Django 2.0.6 on 2018-06-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180610_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='factory_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
