# Generated by Django 2.0.6 on 2018-06-11 10:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180610_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='user',
            name='prop_img_0',
            field=models.ImageField(default='none/noimage.jpg', upload_to='user/prop'),
        ),
        migrations.AddField(
            model_name='user',
            name='prop_img_1',
            field=models.ImageField(default='none/noimage.jpg', upload_to='user/prop'),
        ),
        migrations.AddField(
            model_name='user',
            name='prop_img_2',
            field=models.ImageField(default='none/noimage.jpg', upload_to='user/prop'),
        ),
        migrations.AddField(
            model_name='user',
            name='prop_img_3',
            field=models.ImageField(default='none/noimage.jpg', upload_to='user/prop'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='none/noimage.jpg', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
